#include "init.h"
#include <main.h>
void DMA_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA1EN;

    // UART5 TX
    DMA1_Stream7->CR |= DMA_SxCR_CHSEL_2 | DMA_SxCR_PL_1 | DMA_SxCR_MINC | DMA_SxCR_DIR_0 | DMA_SxCR_TCIE;
    DMA1_Stream7->PAR = (uint32_t)&UART5->DR;
    DMA1_Stream7->FCR = 0;
    // UART5 RX
    DMA1_Stream0->CR |= DMA_SxCR_CHSEL_2 | DMA_SxCR_PL_1 | DMA_SxCR_MINC;
    DMA1_Stream0->PAR = (uint32_t)&UART5->DR;
    DMA1_Stream0->M0AR = (uint32_t)&RxBufferUART5;
    DMA1_Stream0->NDTR = UART5_RX_BUF_SIZE;
    DMA1_Stream0->FCR = 0;

    // UART4 TX
    DMA1_Stream4->CR |=
        DMA_SxCR_CHSEL_2 | DMA_SxCR_PL_1 | DMA_SxCR_PL_0 | DMA_SxCR_MINC | DMA_SxCR_DIR_0 | DMA_SxCR_TCIE;
    DMA1_Stream4->PAR = (uint32_t)&UART4->DR;
    DMA1_Stream4->FCR = 0;

    NVIC_SetPriority(DMA1_Stream0_IRQn, 1);
    NVIC_EnableIRQ(DMA1_Stream0_IRQn);
    NVIC_SetPriority(DMA1_Stream7_IRQn, 1);
    NVIC_EnableIRQ(DMA1_Stream7_IRQn);
    NVIC_SetPriority(DMA1_Stream4_IRQn, 0);
    NVIC_EnableIRQ(DMA1_Stream4_IRQn);
}
void DAC_Init(void)
{
    RCC->APB1ENR |= RCC_APB1ENR_DACEN;
    DAC->CR |= DAC_CR_TSEL1_2 | DAC_CR_TSEL1_1 | DAC_CR_TSEL1_0 | DAC_CR_TEN1;
}

void ADC_Init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
    ADC->CCR |= 1 << 16; // prescaler = 4
    ADC->CCR |= ADC_CCR_TSVREFE;
    ADC1->CR2 |= ADC_CR2_EOCS;
}

void UART_Init(void)
{
    // UART5
    RCC->APB1ENR |= RCC_APB1ENR_UART5EN;
    UART5->CR1 |= USART_CR1_RE | USART_CR1_TE | USART_CR1_UE | USART_CR1_IDLEIE;
    UART5->CR3 |= USART_CR3_DMAT | USART_CR3_DMAR;
    UART5->BRR = 0x187; // 115200, 45Мгц

    NVIC_SetPriority(UART5_IRQn, 1);
    NVIC_EnableIRQ(UART5_IRQn);
    // UART4
    RCC->APB1ENR |= RCC_APB1ENR_UART4EN;
    UART4->BRR = 0x187;
    UART4->CR1 |= USART_CR1_UE | USART_CR1_RE | USART_CR1_TE | USART_CR1_RXNEIE;
    UART4->CR3 |= USART_CR3_DMAT;
    NVIC_SetPriority(UART4_IRQn, 0);
    NVIC_EnableIRQ(UART4_IRQn);
}

void MODBUS_Timer_Init(void)
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
    TIM3->CNT = 1;
    TIM3->PSC = 899;
    TIM3->ARR = 65535;

    TIM3->CCR1 = (MODBUS_T1_5_US / 10);
    TIM3->CCR2 = (MODBUS_T3_5_US / 10);
    TIM3->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E;
    TIM3->DIER |= TIM_DIER_CC1IE | TIM_DIER_CC2IE;

    TIM3->CCMR1 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_0;
    TIM3->CCMR1 |= TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_0;

    TIM3->CR1 |= TIM_CR1_OPM;
    TIM3->EGR |= TIM_EGR_UG;
    TIM3->SR &= ~TIM_SR_UIF;
    NVIC_SetPriority(TIM3_IRQn, 2);
    NVIC_EnableIRQ(TIM3_IRQn);
}

void TIM6_Init(void)
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM6EN;
    TIM6->PSC = 8999;
    TIM6->ARR = 714;
    TIM6->CNT = 0;
    TIM6->CR1 &= ~TIM_CR1_UDIS;
    TIM6->CR1 |= TIM_CR1_URS;
    TIM6->CR1 &= ~TIM_CR1_OPM;
    TIM6->EGR |= TIM_EGR_UG;
    TIM6->SR &= ~TIM_SR_UIF;
    TIM6->DIER |= TIM_DIER_UIE;
    NVIC_SetPriority(TIM6_DAC_IRQn, 2);
    NVIC_EnableIRQ(TIM6_DAC_IRQn);
}

void GPIO_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN | RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOBEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    // PA0-PA5: ADC inputs
    GPIOA->MODER |= GPIO_MODER_MODER0 | GPIO_MODER_MODER1 | GPIO_MODER_MODER2 | GPIO_MODER_MODER3 |
                    GPIO_MODER_MODER4 | GPIO_MODER_MODER5;

    // UART5: PC12 (TX), PD2 (RX)
    GPIOC->MODER &= ~GPIO_MODER_MODER12;
    GPIOC->MODER |= GPIO_MODER_MODER12_1;
    GPIOC->AFR[1] &= ~(0xF << 16);
    GPIOC->AFR[1] |= (8 << 16);
    GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12;

    GPIOD->MODER &= ~GPIO_MODER_MODER2;
    GPIOD->MODER |= GPIO_MODER_MODER2_1;
    GPIOD->AFR[0] &= ~(0xF << 8);
    GPIOD->AFR[0] |= (8 << 8);
    GPIOD->PUPDR &= ~GPIO_PUPDR_PUPDR2;
    GPIOD->PUPDR |= GPIO_PUPDR_PUPDR2_0;

    // UART4: PC10 (TX), PC11 (RX)
    GPIOC->MODER &= ~(GPIO_MODER_MODER10 | GPIO_MODER_MODER11);
    GPIOC->MODER |= GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1;
    GPIOC->AFR[1] &= ~((0xF << 8) | (0xF << 12));
    GPIOC->AFR[1] |= (8 << 8) | (8 << 12);
    GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR11;
    GPIOC->PUPDR &= ~GPIO_PUPDR_PUPDR11;
    GPIOC->PUPDR |= GPIO_PUPDR_PUPDR11_0;

    // PB13: Button (EXTI12)
    GPIOB->MODER &= ~(GPIO_MODER_MODER12 | GPIO_MODER_MODER13);
    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR12 | GPIO_PUPDR_PUPDR13);
    GPIOB->PUPDR |= GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR13_0;
    SYSCFG->EXTICR[3] &= ~SYSCFG_EXTICR4_EXTI12;
    SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI12_PB;
    EXTI->IMR |= EXTI_IMR_MR12;
    EXTI->FTSR |= EXTI_FTSR_TR12;
    EXTI->RTSR &= ~EXTI_RTSR_TR12;
    NVIC_SetPriority(EXTI15_10_IRQn, 3);
    NVIC_EnableIRQ(EXTI15_10_IRQn);

    // PB14, PB15: SOURCE, CONVERTER (outputs)
    GPIOB->MODER &= ~(GPIO_MODER_MODER14 | GPIO_MODER_MODER15);
    GPIOB->MODER |= GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0;
    GPIOB->OTYPER &= ~((1 << 14) | (1 << 15));
    GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14 | GPIO_OSPEEDER_OSPEEDR15;
    GPIOB->BSRR = (1 << (14 + 16)) | (1 << (15 + 16));

    // PB0: JUMPER (input, pull-up)
    GPIOB->MODER &= ~GPIO_MODER_MODER0;
    GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR0;
    GPIOB->PUPDR |= GPIO_PUPDR_PUPDR0_0;

    // PB1, PB2: SOURCE_STATUS, CONVERTER_STATUS (inputs, pull-down)
    GPIOB->MODER &= ~(GPIO_MODER_MODER1 | GPIO_MODER_MODER2);
    GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR1 | GPIO_PUPDR_PUPDR2);
    GPIOB->PUPDR |= GPIO_PUPDR_PUPDR1_1 | GPIO_PUPDR_PUPDR2_1;
}
